name: Generate Snake

on:
  schedule:
    # Runs at 07:00 WIB every day (00:00 UTC)
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: github-snake
          path: dist/github-snake.svg

      - name: Push to output branch
        if: success()
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout -b output
          mv dist/github-snake.svg .
          git add github-snake.svg
          git commit -m "Generate snake animation"
          git push origin output --force
